sudo: false
dist: trusty
branches:
  only:
    - travisCI
matrix:
  include:
    - language: java
      jdk: oraclejdk8
      install:
        - true
      script:
        - mvn clean verify
        - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
        - mvn test
    - language: node_js
      node_js:
        - '8'
        -
      install:
        - npm install
      cache:
        directories:
          - ./node_modules

      script:
        - npm run test
