branches:
  only:
    - travisCI
language: java
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
cache:
  directories:
    - node_modules
before_install:
  - npm i -g npm@latest
script:
  - mvn test
  - npm run lint:ci
  - npm run build:prod
