sudo: required
dist: trusty
branches:
  only:
    - travisCI
matrix:
  include:
    - language: java
      jdk: oraclejdk8
      before_install:
        - chmod +x mvnw
      install:
        - true
      script:
        - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
        - mvn test
    - language: node_js
      node_js:
        - '8'
      cache:
        directories:
          - ./node_modules

      install:
        - npm install

      script:
        - npm run test
