sudo: required
dist: trusty
branches:
  only:
    - travisCI
matrix:
  include:
    - language: java
      jdk: oraclejdk8
      before_install:
        - chmod +x mvnw
      install:
        - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      script:
        - mvn install
        - mvn test
    - language: node

