sudo: required
dist: trusty



addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

matrix:
  include:
    - language: java
      jdk: oraclejdk8
      script:
        - ./mvnw test -B -q
      before_script:
        - cd ./backend/

    - language: node_js
      node_js: stable
      install:
        - npm install
      before_install:
        - cd ./frontend/
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
      script:
        - npm run build
