branches:
  only:
    - travisCI
language: java
install: true

cache:
  directories:
    - node_modules
before_install:
  - npm i -g npm@latest
script:
  - mvn install
  - npm run lint:ci
  - npm run build:prod
